<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\CategoryController::viewCategorypage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\CommentController::viewCommentPage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController::Vote' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController::viewHomepage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\ProfileController::viewProfilepage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\RegisterController::userRegister' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\SessionsController::destroySession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\SessionsController::newSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\CategoryController:viewCategorypage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\CommentController:viewCommentPage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController:Vote' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\HomeController:viewHomepage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\ProfileController:viewProfilepage' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\RegisterController:userRegister' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\SessionsController:destroySession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}, 'App\\Controller\\SessionsController:newSession' => function () {
    return ($this->privates['.service_locator.XMePXeM'] ?? $this->load('get_ServiceLocator_XMePXeMService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
