<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYfr5RAx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYfr5RAx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYfr5RAx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYfr5RAx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYfr5RAx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Yfr5RAx',
    'container.build_id' => '849345c4',
    'container.build_time' => 1541470883,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYfr5RAx');
